export const Robots=[{
    id:1,
name:' princeley',
age:34
},
{
    id:2,
    name:' steno',
    age:33
    }, 
    {
        id:3,
        name:'hulk',
        age:34
        },
        {
            id:4,
            name:'ley',
            age:109
            },
            {
                id:5,
                name:'Onu ',
                age:30
                },
                {
                    id:7,
                    name:'hero',
                    age:46
                    },
                    {
                        id:9,
                        name:'shima',
                        age:34
                        },
                        {
                            id:10,
                            name:'wire',
                            age:38
                            },
                            {
                                id:12,
                                name:'von',
                                age:39
                                },
                                {
                                    id:45,
                                    name:'xen',
                                    age:65
                                    },]